package Pojo;
// Generated 2/11/2015 09:58:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer marCodigo;
     private String marNombre;
     private String marDescripcion;
     private Set productos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(String marNombre) {
        this.marNombre = marNombre;
    }
    public Marca(String marNombre, String marDescripcion, Set productos) {
       this.marNombre = marNombre;
       this.marDescripcion = marDescripcion;
       this.productos = productos;
    }
   
    public Integer getMarCodigo() {
        return this.marCodigo;
    }
    
    public void setMarCodigo(Integer marCodigo) {
        this.marCodigo = marCodigo;
    }
    public String getMarNombre() {
        return this.marNombre;
    }
    
    public void setMarNombre(String marNombre) {
        this.marNombre = marNombre;
    }
    public String getMarDescripcion() {
        return this.marDescripcion;
    }
    
    public void setMarDescripcion(String marDescripcion) {
        this.marDescripcion = marDescripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


