package Pojo;
// Generated 2/11/2015 09:58:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userid;
     private String username;
     private String userpass;
     private String userdoc;
     private String userusu;
     private String usertele;
     private String userdir;
     private String usercorreo;
     private String userestado;
     private Set movimientoses = new HashSet(0);
     private Set auditorias = new HashSet(0);
     private Set roleusrs = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String userpass, String userusu, String userestado) {
        this.username = username;
        this.userpass = userpass;
        this.userusu = userusu;
        this.userestado = userestado;
    }
    public Users(String username, String userpass, String userdoc, String userusu, String usertele, String userdir, String usercorreo, String userestado, Set movimientoses, Set auditorias, Set roleusrs) {
       this.username = username;
       this.userpass = userpass;
       this.userdoc = userdoc;
       this.userusu = userusu;
       this.usertele = usertele;
       this.userdir = userdir;
       this.usercorreo = usercorreo;
       this.userestado = userestado;
       this.movimientoses = movimientoses;
       this.auditorias = auditorias;
       this.roleusrs = roleusrs;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUserpass() {
        return this.userpass;
    }
    
    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }
    public String getUserdoc() {
        return this.userdoc;
    }
    
    public void setUserdoc(String userdoc) {
        this.userdoc = userdoc;
    }
    public String getUserusu() {
        return this.userusu;
    }
    
    public void setUserusu(String userusu) {
        this.userusu = userusu;
    }
    public String getUsertele() {
        return this.usertele;
    }
    
    public void setUsertele(String usertele) {
        this.usertele = usertele;
    }
    public String getUserdir() {
        return this.userdir;
    }
    
    public void setUserdir(String userdir) {
        this.userdir = userdir;
    }
    public String getUsercorreo() {
        return this.usercorreo;
    }
    
    public void setUsercorreo(String usercorreo) {
        this.usercorreo = usercorreo;
    }
    public String getUserestado() {
        return this.userestado;
    }
    
    public void setUserestado(String userestado) {
        this.userestado = userestado;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }
    public Set getAuditorias() {
        return this.auditorias;
    }
    
    public void setAuditorias(Set auditorias) {
        this.auditorias = auditorias;
    }
    public Set getRoleusrs() {
        return this.roleusrs;
    }
    
    public void setRoleusrs(Set roleusrs) {
        this.roleusrs = roleusrs;
    }




}


